# Generated by Django 2.2.12 on 2022-04-01 11:22

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='paid_courses',
            new_name='courseActivated',
        ),
    ]
