# Generated by Django 2.2.12 on 2022-04-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220401_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='relatedCourse',
            new_name='rlCourses',
        ),
    ]
