# Generated by Django 2.2.12 on 2022-04-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220401_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_uuid',
            new_name='courseUUID',
        ),
    ]
