# Generated by Django 2.2.12 on 2022-04-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220401_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='sector_image',
            new_name='sector_img',
        ),
    ]
